[config.wallpaper]
command = "swww"

# AGS / UI Custom Templates
[templates.ags]
input_path = '~/.config/matugen/templates/ags.scss'
output_path = '~/.local/state/ags/scss/_material.scss'
post_hook='agsv1 run-js "handleStyles(false);"'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

# GTK Cursed Stuff

[templates.gradience]
input_path = '~/.config/matugen/templates/gradience.json'
output_path = '~/.cache/ags/user/generated/gradience/gradience.json'
post_hook='mkdir -p ~/.config/presets && rm -rf ~/.config/gtk-4.0 ~/.config/gtk-3.0 && gradience-cli apply -p ~/.cache/ags/user/generated/gradience/gradience.json --gtk both'

# Regular GTK Theming Stuff #! Fallback

# [templates.gtk3]
# input_path = '~/.config/matugen/templates/gtk-colors.css'
# output_path = '~/.config/gtk-3.0/colors.css'
# post_hook= 'echo "@import 'colors.css';" >> ~/.config/gtk-3.0/gtk.css'

# [templates.gtk4]
# input_path = '~/.config/matugen/templates/gtk-colors.css'
# output_path = '~/.config/gtk-4.0/colors.css'
# post_hook= 'echo "@import 'colors.css';" >> ~/.config/gtk-4.0/gtk.css'

# Hyprland 

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock.conf'
output_path = '~/.config/hypr/hyprlock.conf'
post_hook = 'hyprctl reload'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'

# QT 

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

# Shell / Terminal Stuff

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'

[templates.starship]
input_path = '~/.config/matugen/templates/starship-colors.toml'
output_path = '~/.config/starship.toml'
post_hook = 'starship init zsh > ~/.zshrc'

# Custom Apps 

[templates.spicetify]
input_path = '~/.config/matugen/templates/colors.ini'
output_path = '~/.config/spicetify/Themes/Comfy/color.ini'

[templates.obsidian]
input_path = '~/.config/matugen/templates/obsidian.css'
output_path = '/mnt/Data/General-Archive/obsidian/.obsidian/snippets/material-you.css'

[templates.vscode]
input_path = '~/.config/matugen/templates/vscode-color-theme.json'
output_path = '~/.windsurf/extensions/theme-material-you/themes/vscode.json'
post_hook = 'cp ~/.config/matugen/other/vscode-package.json ~/.windsurf/extensions/theme-material-you/package.json'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.discord]
input_path = '~/.config/matugen/templates/discord.css'
output_path = '~/.config/vesktop/themes/material-you.css'

[templates.telegram]
input_path = '~/.config/matugen/templates/telegram-colors.tdesktop-theme'
output_path = '~/.config/telegram-desktop/themes/material-you.tdesktop-theme'
