[config]
reload_apps = true

[config.wallpaper]
command = "swww"
set = false

[templates.ags]
input_path = "~/.config/matugen/templates/ags.scss"
output_path = "~/.local/state/ags/scss/_material.scss"
post_hook = "agsv1 --run-js 'globalThis.handleStyles(true)'"


[templates.foot]
input_path = "~/.config/matugen/templates/foot.ini"
output_path = "~/.config/foot/colors.ini"


[templates.rofi]
input_path = "~/.config/matugen/templates/rofi-colors.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.gradience]
input_path = "~/.config/matugen/templates/gradience.json"
output_path = "~/.cache/ags/user/generated/gradience/gradience.json"
post_hook = "gradience-cli apply -p ~/.cache/ags/user/generated/gradience/gradience.json --gtk both"

[templates.hyprlock]
input_path = "~/.config/matugen/templates/hyprlock.conf"
output_path = "~/.config/hypr/hyprlock.conf"
post_hook = "hyprctl reload"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.cache/ags/user/generated/colors.conf"

[templates.qt5ct]
input_path = "~/.config/matugen/templates/qtct-colors.conf"
output_path = "~/.config/qt5ct/colors/matugen.conf"

[templates.qt6ct]
input_path = "~/.config/matugen/templates/qtct-colors.conf"
output_path = "~/.config/qt6ct/colors/matugen.conf"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.cache/ags/user/generated/kitty-colors.conf"

[templates.starship]
input_path = "~/.config/matugen/templates/starship-colors.toml"
output_path = "~/.config/starship.toml"
post_hook = "starship init zsh > ~/.zshrc"

[templates.heroic]
input_path = "~/.config/matugen/templates/heroic-theme.css"
output_path = "~/.cache/ags/user/generated/heroic-colors.css"

# [templates.obsidian]
# input_path = "~/.config/matugen/templates/obsidian.css"
# output_path = "/mnt/Data/General-Archive/obsidian/.obsidian/snippets/material-you.css"

[templates.vscode]
input_path = "~/.config/matugen/templates/vscode-color-theme.json"
output_path = "~/.windsurf/extensions/theme-material-you/themes/vscode.json"
